console_title_template = '{{regexFind "^[^.]*" .HostName}}{{if .Root}} :: root{{end}} :: {{.PWD}}'
version = 3
final_space = true

[palette]
  black = '#2F2F2F'
  blue = '#4696DA'
  darkblue = '#2676BA'
  green = '#6CA35E'
  grey = '#7A7A7A'
  orange = '#F3AE35'
  purple = '#8A4FFF'
  red = '#E84855'
  white = '#FAFAFA'
  yellow = '#FFCE5C'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:green'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}']

[transient_prompt]
  template = '{{now | date "15:04"}}❯ '
  foreground = 'p:green'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = '' # '░▒'
    template = ' {{if .WSL}} on {{end}}{{.Icon}} <p:grey></>'
    foreground = 'p:white'
    background = 'p:black'
    type = 'os'

  [[blocks.segments]]
    style = 'diamond'
    template = ' '
    foreground = 'p:yellow'
    background = 'p:black'
    type = 'root'

  [[blocks.segments]]
    style = 'diamond'
    template = ' {{if ne .Env.USERNAME .UserName}}{{regexFind "^[^@]*" .UserName}}{{end}}{{if .SSHSession}}  {{regexFind "^[^.]*" .HostName}}{{end}}{{if or (ne .Env.USERNAME .UserName) (.SSHSession)}}<p:grey> </>{{end}}'
    foreground = 'p:yellow'
    background = 'p:black'
    foreground_templates = ['{{if eq .UserName "root"}}p:red{{end}}']
    type = 'session'

  [[blocks.segments]]
    style = 'diamond'
    template = ' <p:orange></> {{path .Path .Location}}'
    foreground = 'p:darkblue'
    background = 'p:black'
    type = 'path'

    [blocks.segments.properties]
      style = 'agnoster_short'
      edge_format = '<p:blue>%s</>'
      folder_format = '<p:darkblue>%.20s</>'
      folder_icon = '…'
      folder_separator_icon = '<p:grey>/</>'
      gitdir_format = '<p:blue>%s</>'
      home_icon = ' '
      max_depth = 3

      [blocks.segments.properties.mapped_locations]
        "~/projects" = ' '
        "~/workspace" = ' '
        "/tmp" = ' '

  [[blocks.segments]]
    style = 'diamond'
    template = ' <p:grey></> {{.UpstreamIcon}}{{.HEAD}}{{if .BranchStatus}} {{.BranchStatus}}{{end}}{{if .Working.Changed}}<p:red>  {{.Working.String}}</>{{end}}{{if and (.Working.Changed) (.Staging.Changed)}} |{{end}}{{if .Staging.Changed}}<p:green>  {{.Staging.String}}</>{{end}}{{if gt .StashCount 0}}  {{.StashCount}}{{end}}'
    foreground = 'p:green'
    background = 'p:black'
    type = 'git'
    foreground_templates = [
      '{{if or (.Working.Changed) (.Staging.Changed)}}p:yellow{{end}}',
      '{{if gt .Ahead 0}}p:blue{{end}}',
      '{{if gt .Behind 0}}p:purple{{end}}'
    ]

    [blocks.segments.properties]
      branch_max_length = 15
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    style = 'diamond'
    template = ' '
    foreground = 'p:black'
    background = 'transparent'
    type = 'text'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '<p:grey>·</>'
  overflow = 'hide'

  [[blocks.segments]]
    style = 'diamond'
    template = ' '
    foreground = 'p:black'
    background = 'transparent'
    type = 'text'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    style = 'diamond'
    template = ' <p:grey></> '
    foreground = 'p:blue'
    background = 'p:black'
    type = 'go'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    template = ' <p:grey></> '
    foreground = 'p:yellow'
    background = 'p:black'
    type = 'lua'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    template = ' {{if .PackageManagerIcon}}{{.PackageManagerIcon}} {{end}}{{.Full}}<p:grey></> '
    foreground = 'p:green'
    background = 'p:black'
    type = 'node'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    template = ' {{if .Error}}{{.Error}}{{else}}{{if .Venv}}{{.Venv}} {{end}}{{.Full}}{{end}}<p:grey></> '
    foreground = 'p:green'
    background = 'p:black'
    type = 'python'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    template = ' <p:grey></> '
    foreground = 'p:red'
    background = 'p:black'
    type = 'ruby'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    template = ' <p:grey></> '
    foreground = 'p:red'
    background = 'p:black'
    type = 'rust'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    template = ' {{if .Unsupported}}{{else}}{{.Full}}{{end}}<p:grey></> '
    foreground = 'p:blue'
    background = 'p:black'
    type = 'dotnet'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = '' # '▒░'
    template = '{{.CurrentDate | date "15:04:05"}}<p:blue>  </>'
    foreground = 'p:grey'
    background = 'p:black'
    type = 'time'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    foreground = 'p:green'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}']

[[blocks]]
  type = 'rprompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    style = 'plain'
    template = ' ❮'
    foreground = 'p:grey'
    type = 'text'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{.FormattedMs}}<p:white>  </>'
    foreground = 'p:yellow'
    type = 'executiontime'

    [blocks.segments.properties]
      style = 'round'
      threshold = 3000

  [[blocks.segments]]
    style = 'plain'
    template = '{{if gt .Code 0}}  {{.Code}}{{else}} {{end}}'
    foreground = 'p:green'
    type = 'status'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}']

    [blocks.segments.properties]
      always_enabled = true

[[tooltips]]
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{.Profile}}{{if .Region}}@{{.Region}}{{end}} '
  foreground = 'p:black'
  background = 'p:orange'
  type = 'aws'
  tips = ['aws', 'terraform']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{.Name}} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  tips = ['az', 'terraform']

  [tooltips.properties]
    display_default = true
