# disable the ctrl+s idiocy
stty -ixon

# use non-duplicate arrays for paths
typeset -TU INFOPATH infopath
typeset -TU LD_LIBRARY_PATH ld_library_path
typeset -U fpath manpath path

# setup the brew environment variables if it's installed
if [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  brewp="/home/linuxbrew/.linuxbrew"
elif [[ -x /opt/homebrew/bin/brew ]]; then
  brewp="/opt/homebrew"
fi

if [[ -x ${brewp}/bin/brew ]] && [[ $- == *i* ]]; then
  grep -q "${brewp}" <<<"${PATH}" || eval "$(${brewp}/bin/brew shellenv)"
  for d in ${brewp}/opt/*/libexec/gnubin ${brewp}/opt/python*/libexec/bin; do
    path=("$d" $path); export PATH
  done 2>/dev/null
  fpath=("${brewp}/share/zsh/site-functions" $fpath); export PATH
  unset brewp || :
fi