ANTIDOTE_HOME=~/.cache/antidote
MAGIC_ENTER_GIT_COMMAND=' git status --show-stash -s; ls'
MAGIC_ENTER_OTHER_COMMAND=' ls'
ZDOTDIR=~/.config/zsh
[[ "$SSH_TTY" ]] && ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_CONFIG=~/.config/tmux/tmux.conf

# History
HISTDUP=erase
HIST_STAMPS='%F.%T'
HISTORY_IGNORE='(bg *|btop|clear|exit|fg *|hist*|hs*|htop|jobs|k9|l[als] *'
HISTORY_IGNORE+='|man *|pwd|top *|uptime)'
HISTFILE=$ZDOTDIR/.zsh_history

ZSH_COMPDUMP=${XDG_CACHE_HOME:-$HOME/.cache}/zcompdump
#CASE_SENSITIVE='true' # Uncomment to use case-sensitive completion.
HYPHEN_INSENSITIVE='true' # Uncomment to use hyphen-insensitive completion.
#ENABLE_CORRECTION='true' # Uncomment to enable command auto-correction.
COMPLETION_WAITING_DOTS='true' # Uncomment to display red dots while waiting
# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
#DISABLE_UNTRACKED_FILES_DIRTY='true'

# Environment
export FZF_DEFAULT_COMMAND="fd --type file --color=always"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" FZF_DEFAULT_OPTS="--ansi"
export HOMEBREW_BUNDLE_FILE="$HOME/.config/Brewfile" HOMEBREW_INSTALL_CLEANUP=1
export HOMEBREW_NO_ENV_HINTS=1 #HOMEBREW_VERIFY_ATTESTATIONS=1

# Compilation flags
#export ARCHFLAGS='-arch x86_64'
export PYTHONDONTWRITEBYTECODE=1
export GOPATH="${HOME}/.local/share/go"