ANTIDOTE_HOME=~/.cache/antidote
MAGIC_ENTER_GIT_COMMAND=' ls; git status -u .'
MAGIC_ENTER_OTHER_COMMAND=' ls'
ZDOTDIR=~/.config/zsh
[[ "$SSH_TTY" ]] && ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_CONFIG=~/.config/tmux/tmux.conf