first_name_only = false
show_receipts = true
bell = true
passphrase = "aawtrQsfyh@69"
colored_messages = true
default_keybindings = true

[notifications]
enabled = true
show_message_text = true
show_message_chat = true
show_reactions = true
mute_reactions_bell = true

[user]
display_name = "dperson"

[keybindings]

[keybindings.anywhere]
ctrl-c = "copy_message selected"
ctrl-q = "quit"

[keybindings.normal]
ctrl-j = ""
ctrl-k = "kill_line"
ctrl-n = "select_channel next"
ctrl-p = "select_channel previous"
alt-c = "toggle_channel_modal"
up = "select_message previous entry"
down = "select_message next entry"

[keybindings.channel_modal]
ctrl-j = ""
ctrl-k = ""
ctrl-n = "select_channel_modal next"
ctrl-p = "select_channel_modal previous"

[keybindings.message_selected]
alt-w = "copy_message selected"
ctrl-t = "react :thumbsup:"
ctrl-h = "react ❤️"
